name: sentiment_env
channels:
  - conda-forge
dependencies:
  - python=3.10.10
  - pip=22.3.1
  - numpy=1.23.4
  - flask=2.2.2
  - nltk=3.7
  - scikit-learn=1.1.3
  - beautifulsoup4=4.11.1
  - wordcloud=1.9.2
  - lxml=4.9.1
prefix:
